
services:
    byceps-redis:
        image: "redis:7"
        container_name: byceps-redis
        restart: always
        volumes:
            - ${VOLUME_BASE_PATH}/byceps-redis/conf:/usr/local/etc/redis
        networks:
            - database-net

    byceps-db:
        image: postgres:15
        container_name: byceps-db
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_DB: ${POSTGRES_DB}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ${VOLUME_BASE_PATH}/byceps-db/data:/var/lib/postgresql/data
        networks:
            - database-net

    byceps-app-site:
        image: ghcr.io/bergi9/byceps:main
        container_name: byceps-app-site
        restart: unless-stopped
        depends_on:
            - byceps-redis
            - byceps-db
        environment:
            APP_MODE: site
            SECRET_KEY: ${SECRET_KEY}
            SITE_ID: ${SITE_ID}
            BYCEPS_CONFIG: /home/byceps/app/config/${BYCEPS_CONFIG_FILE}
            REDIS_URL: "redis://byceps-redis/0"
            SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@byceps-db/${POSTGRES_DB}"
        volumes:
            - ${VOLUME_BASE_PATH}/byceps-app/config:/home/byceps/app/config
            # used for nginx sharing
            - ${VOLUME_BASE_PATH}/byceps-app/data:/home/byceps/app/data
            - ${VOLUME_BASE_PATH}/byceps-app/sites:/home/byceps/app/sites
        networks:
            - database-net
            - nginx-net

    byceps-app-admin:
        image: ghcr.io/bergi9/byceps:main
        container_name: byceps-app-admin
        restart: unless-stopped
        depends_on:
            - byceps-redis
            - byceps-db
        environment:
            APP_MODE: admin
            SECRET_KEY: ${SECRET_KEY}
            SITE_ID: ${SITE_ID}
            BYCEPS_CONFIG: /home/byceps/app/config/${BYCEPS_CONFIG_FILE}
            REDIS_URL: "redis://byceps-redis/0"
            SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@byceps-db/${POSTGRES_DB}"
        volumes:
            - ${VOLUME_BASE_PATH}/byceps-app/config:/home/byceps/app/config
            # used for nginx sharing
            - ${VOLUME_BASE_PATH}/byceps-app/data:/home/byceps/app/data
            - ${VOLUME_BASE_PATH}/byceps-app/sites:/home/byceps/app/sites
        networks:
            - database-net
            - nginx-net

    byceps-app-worker:
        image: ghcr.io/bergi9/byceps:main
        container_name: byceps-app-worker
        restart: unless-stopped
        command: ["./worker.py"]
        depends_on:
            - byceps-redis
            - byceps-db
        environment:
            APP_MODE: base
            SECRET_KEY: ${SECRET_KEY}
            SITE_ID: ${SITE_ID}
            BYCEPS_CONFIG: /home/byceps/app/config/${BYCEPS_CONFIG_FILE}
            REDIS_URL: "redis://byceps-redis/0"
            SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@byceps-db/${POSTGRES_DB}"
        volumes:
            - ${VOLUME_BASE_PATH}/byceps-app/config:/home/byceps/app/config
            # used for nginx sharing
            - ${VOLUME_BASE_PATH}/byceps-app/data:/home/byceps/app/data
            - ${VOLUME_BASE_PATH}/byceps-app/sites:/home/byceps/app/sites
        networks:
            - database-net
            - nginx-net

    byceps-nginx:
        image: nginx:alpine
        container_name: byceps-nginx
        restart: always
        depends_on:
            - byceps-app-site
            - byceps-app-admin
        ports:
            - "${NGINX_PUBLIC_PORT}:80"
        volumes:
            - ${VOLUME_BASE_PATH}/byceps-nginx:/etc/nginx
            # for byceps static files sharing to nginx
            - ${VOLUME_BASE_PATH}/byceps-app/data:/var/www/byceps/data
            - ${VOLUME_BASE_PATH}/byceps-app/sites:/var/www/byceps/sites
            - ${VOLUME_BASE_PATH}/byceps-nginx/cache:/var/www/cache
        networks:
            - nginx-net

networks:
    database-net:
    nginx-net:
